# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a97c6b5244c5c4936d392b350cada52bfcc4eeb99bed8570d84be4ab72db55495e468653da707e0976d9b60a599a6630f9eeaac2e31fb880d30ff878ef6512f7

test:
  secret_key_base: bad7e1b190579534a7e14ca6e5e46a2d2497f7532e37914ce1aafb1bddf339fbb75d23d8a3a9ef40216741b778605c6ae40619b36ac28458b938c6ec4f93e598

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
